spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vulnview
    username: ${DB_USERNAME:vulnview}
    password: ${DB_PASSWORD:vulnview}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.vulnview: TRACE
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.flywaydb: DEBUG
  file:
    name: target/spring.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

ossindex:
  username: ${OSSINDEX_USERNAME:test}
  token: ${OSSINDEX_TOKEN:test} 